module.exports = {
    ACTION_ADD: "ACTION_ADD",
    ACTION_REMOVE: "ACTION_REMOVE",
    ACTION_EDIT: "ACTION_EDIT",
    ACTION_UPDATE: "ACTION_UPDATE",
    //--------------------------//
    GET_STUDENT: "GET_STUDENT",
    CREATE_STUDENT: "CREATE_STUDENT",
    UPDATE_STUDENT: "UPDATE_STUDENT",
    DELETE_STUDENT: "DELETE_STUDENT",

    GET_USERS: "GET_USERS",
    GET_COURSE:"GET_COURSE",
}
